### PR TITLE
Issue #62 - Allow http proxy values to be supplied through values.yaml

### PR DESCRIPTION
**Pull request by mookkiah**
It is better to leave the JVM options to be configurable so that the end user can configure more options not just proxy.
Also providing env configurable in values.yaml opens up opportunities for the users.
Updated the documentation to reflect the changes
Tested the image and helm chart in Kubernetes.

Note: Readme markdowns are formatted by the IDE. I touched up to not to have so many.

### CODE REVIEW

**Comment by mookkiah** [comment]
@stevespringett Please review and give your comments.

**Comment by mookkiah** [comment]
@roelofjansen Please review. 
I see Ujjwal Patil as maintainer for the chart but I couldnt find the username matching the name.

**Comment by mookkiah** [comment]
@stevespringett Please let me know if there is any reason for keeping this PR open. I am happy to help and delete my fork.

**Comment by stevespringett** [comment]
Delayed due to moving. Thanks for the PR. Much appreciated.

**Pull request merged**
