### PR TITLE
Helm chart

### PR DESCRIPTION
**Pull request by ujjwalpatil**
Created Helm chart for deploying NIST mirror as service in k8s. 
Thanks for the help @rljohnsn

### CODE REVIEW

**Comment by stevespringett** [comment]
Thanks for the PR. Could you modify the README so that it separates out the normal usage from the K8 usage. This is not a K8 project, it's actually just a java utility that can be run from the command line with an optional container runtime. Having k8 on top of that is great, but I don't want to confuse users about the goals of the project.

I would recommend creating a directory for k8 and putting the relevant readme and configuration in there

**Comment by ujjwalpatil** [comment]
Steve, as suggested, I have moved all charts files to k8s top directory. Please let me know if that is works.

**Comment by stevespringett** [comment]
Thanks for the reminder and PR.

**Pull request merged**
